menu = [
    {"kategori": "Makanan", "nama": "Mie Ayam", "harga": 10000},
    {
        "kategori": "Makanan",
        "nama": "Mie Ayam",
        "harga": 12000,
        "cto": "Extra Suwiran Ayam",
    },
    {"kategori": "Makanan", "nama": "Bakso", "harga": 10000},
    {"kategori": "Makanan", "nama": "Bakso", "harga": 12000, "cto": "Porsi Jumbo"},
    {"kategori": "Makanan", "nama": "Bakso", "harga": 12000, "cto": "Extra Pentol"},
    {"kategori": "Makanan", "nama": "Ayam Geprek", "harga": 7000},
    {"kategori": "Makanan", "nama": "Ayam", "harga": 6000},
    {"kategori": "Makanan", "nama": "Ayam", "harga": 10000, "cto": "Plus Nasi"},
    {"kategori": "Makanan", "nama": "Ayam Geprek", "harga": 7000, "cto": "Level 1"},
    {"kategori": "Makanan", "nama": "Ayam Geprek", "harga": 7000, "cto": "Level 2"},
    {"kategori": "Makanan", "nama": "Ayam Geprek", "harga": 7000, "cto": "Level 3"},
    {"kategori": "Makanan", "nama": "Ayam Geprek", "harga": 7000, "cto": "Level 4"},
    {
        "kategori": "Makanan",
        "nama": "Ayam Geprek",
        "harga": 12000,
        "cto": "Level 1 + Nasi",
    },
    {
        "kategori": "Makanan",
        "nama": "Ayam Geprek",
        "harga": 12000,
        "cto": "Level 2 + Nasi",
    },
    {
        "kategori": "Makanan",
        "nama": "Ayam Geprek",
        "harga": 12000,
        "cto": "Level 3 + Nasi",
    },
    {
        "kategori": "Makanan",
        "nama": "Ayam Geprek",
        "harga": 12000,
        "cto": "Level 4 + Nasi",
    },
    {
        "kategori": "Makanan",
        "nama": "Ayam Geprek",
        "harga": 10000,
        "cto": "Mozarella",
    },
    {
        "kategori": "Makanan",
        "nama": "Ayam Geprek",
        "harga": 15000,
        "cto": "Mozarella + Nasi",
    },
    {
        "kategori": "Makanan",
        "nama": "Ayam Penyet",
        "harga": 17000,
    },
    {
        "kategori": "Makanan",
        "nama": "Ayam Bakar",
        "harga": 17000,
    },
    {
        "kategori": "Minuman",
        "nama": "Es Teh",
        "harga": 5000,
        "cto": "Tawar",
        "ukuran": "M",
    },
    {
        "kategori": "Minuman",
        "nama": "Es Teh",
        "harga": 7000,
        "cto": "Tawar",
        "ukuran": "L",
    },
    {
        "kategori": "Minuman",
        "nama": "Es Teh",
        "harga": 5000,
        "cto": "Manis",
        "ukuran": "M",
    },
    {
        "kategori": "Minuman",
        "nama": "Es Teh",
        "harga": 7000,
        "cto": "Manis",
        "ukuran": "L",
    },
    {"kategori": "Minuman", "nama": "Jus Jeruk", "harga": 5000, "ukuran": "M"},
    {"kategori": "Minuman", "nama": "Jus Jeruk", "harga": 7000, "ukuran": "L"},
    {"kategori": "Minuman", "nama": "Jus Apel", "harga": 5000, "ukuran": "M"},
    {"kategori": "Minuman", "nama": "Jus Apel", "harga": 7000, "ukuran": "L"},
    {"kategori": "Minuman", "nama": "Kopi Hitam", "harga": 5000, "cto": "Hangat"},
    {"kategori": "Minuman", "nama": "Kopi Hitam", "harga": 5000, "cto": "Dingin"},
    {"kategori": "Minuman", "nama": "Cappuccino", "harga": 5000, "cto": "Hangat"},
    {"kategori": "Minuman", "nama": "Cappuccino", "harga": 5000, "cto": "Dingin"},
    {"kategori": "Minuman", "nama": "Teh Tarik", "harga": 5000, "ukuran": "M"},
    {"kategori": "Minuman", "nama": "Teh Tarik", "harga": 7000, "ukuran": "L"},
    {"kategori": "Minuman", "nama": "Matcha", "harga": 5000, "ukuran": "M"},
    {"kategori": "Minuman", "nama": "Matcha", "harga": 7000, "ukuran": "L"},
    {"kategori": "Makanan", "nama": "Nasi Goreng", "harga": 15000},
    {
        "kategori": "Makanan",
        "nama": "Nasi Goreng Special",
        "harga": 20000,
        "cto": "Seafood",
    },
    {"kategori": "Makanan", "nama": "Mie Goreng", "harga": 12000},
    {"kategori": "Makanan", "nama": "Mie Goreng Aceh", "harga": 15000, "cto": "Pedas"},
    {"kategori": "Makanan", "nama": "Sate Ayam", "harga": 8000, "cto": "Bumbu Kacang"},
    {"kategori": "Makanan", "nama": "Sate Kambing", "harga": 12000, "cto": "Keju"},
    {"kategori": "Makanan", "nama": "Soto Ayam", "harga": 10000},
    {"kategori": "Makanan", "nama": "Soto Betawi", "harga": 12000, "cto": "Empal"},
    {"kategori": "Makanan", "nama": "Rendang", "harga": 18000},
    {"kategori": "Makanan", "nama": "Gado-Gado", "harga": 15000},
    {"kategori": "Minuman", "nama": "Es Campur", "harga": 8000, "ukuran": "M"},
    {"kategori": "Minuman", "nama": "Es Campur", "harga": 12000, "ukuran": "L"},
    {"kategori": "Minuman", "nama": "Es Buah", "harga": 10000, "ukuran": "M"},
    {"kategori": "Minuman", "nama": "Es Buah", "harga": 15000, "ukuran": "L"},
    {
        "kategori": "Minuman",
        "nama": "Lemon Tea",
        "harga": 6000,
        "cto": "Manis",
        "ukuran": "M",
    },
    {
        "kategori": "Minuman",
        "nama": "Lemon Tea",
        "harga": 8000,
        "cto": "Manis",
        "ukuran": "L",
    },
    {"kategori": "Minuman", "nama": "Milkshake Coklat", "harga": 10000, "ukuran": "M"},
    {"kategori": "Minuman", "nama": "Milkshake Coklat", "harga": 12000, "ukuran": "L"},
    {
        "kategori": "Minuman",
        "nama": "Smoothie Strawberry",
        "harga": 12000,
        "ukuran": "M",
    },
    {
        "kategori": "Minuman",
        "nama": "Smoothie Strawberry",
        "harga": 15000,
        "ukuran": "L",
    },
    {"kategori": "Makanan", "nama": "Nasi Kuning", "harga": 12000},
    {"kategori": "Makanan", "nama": "Nasi Uduk", "harga": 10000},
    {"kategori": "Makanan", "nama": "Nasi Padang", "harga": 15000, "cto": "Rendang"},
    {"kategori": "Makanan", "nama": "Capcay Goreng", "harga": 12000},
    {"kategori": "Makanan", "nama": "Bubur Ayam", "harga": 8000},
    {"kategori": "Makanan", "nama": "Martabak Telur", "harga": 18000},
    {"kategori": "Makanan", "nama": "Kwetiau Goreng", "harga": 13000},
    {"kategori": "Makanan", "nama": "Sop Buntut", "harga": 25000},
    {
        "kategori": "Makanan",
        "nama": "Sate Padang",
        "harga": 15000,
        "cto": "Daging Sapi",
    },
    {"kategori": "Minuman", "nama": "Milk Tea", "harga": 10000, "ukuran": "M"},
    {"kategori": "Minuman", "nama": "Milk Tea", "harga": 12000, "ukuran": "L"},
    {"kategori": "Minuman", "nama": "Green Tea Latte", "harga": 13000, "ukuran": "M"},
    {"kategori": "Minuman", "nama": "Green Tea Latte", "harga": 15000, "ukuran": "L"},
    {
        "kategori": "Minuman",
        "nama": "Strawberry Smoothie",
        "harga": 12000,
        "ukuran": "M",
    },
    {
        "kategori": "Minuman",
        "nama": "Strawberry Smoothie",
        "harga": 15000,
        "ukuran": "L",
    },
    {"kategori": "Minuman", "nama": "Avocado Juice", "harga": 12000, "ukuran": "M"},
    {"kategori": "Minuman", "nama": "Avocado Juice", "harga": 15000, "ukuran": "L"},
    {"kategori": "Minuman", "nama": "Mocha", "harga": 12000, "cto": "Dingin"},
    {"kategori": "Minuman", "nama": "Latte", "harga": 12000, "cto": "Hangat"},
    {"kategori": "Minuman", "nama": "Cendol", "harga": 10000, "ukuran": "M"},
    {"kategori": "Minuman", "nama": "Cendol", "harga": 12000, "ukuran": "L"},
    {"kategori": "Makanan", "nama": "Mie Goreng", "harga": 12000},
    {"kategori": "Makanan", "nama": "Mie Goreng Aceh", "harga": 15000, "cto": "Pedas"},
    {
        "kategori": "Makanan",
        "nama": "Mie Goreng Seafood",
        "harga": 18000,
        "cto": "Topping Mix Seafood",
    },
    {
        "kategori": "Makanan",
        "nama": "Mie Goreng Special",
        "harga": 16000,
        "cto": "Telur + Ayam + Sayuran",
    },
    {
        "kategori": "Makanan",
        "nama": "Mie Goreng Sosis",
        "harga": 14000,
        "cto": "Sosis Panggang",
    },
    {
        "kategori": "Makanan",
        "nama": "Mie Goreng Enak",
        "harga": 16000,
        "cto": "Telur + Udang + Sate Ayam",
    },
    {
        "kategori": "Makanan",
        "nama": "Mie Goreng Cabe Rawit",
        "harga": 15000,
        "cto": "Pedas Banget",
    },
    {
        "kategori": "Makanan",
        "nama": "Mie Goreng Jumbo Seafood",
        "harga": 20000,
        "cto": "Porsi Besar + Mix Seafood",
    },
    {
        "kategori": "Makanan",
        "nama": "Mie Goreng Gila",
        "harga": 18000,
        "cto": "Topping Segala Ada",
    },
    {
        "kategori": "Makanan",
        "nama": "Mie Goreng Mantap",
        "harga": 16000,
        "cto": "Krispi Ayam",
    },
    {
        "kategori": "Makanan",
        "nama": "Mie Goreng Keju",
        "harga": 17000,
        "cto": "Taburan Keju Mozarella",
    },
    {
        "kategori": "Makanan",
        "nama": "Mie Goreng Rempah",
        "harga": 16000,
        "cto": "Bumbu Rempah Pilihan",
    },
    {
        "kategori": "Makanan",
        "nama": "Nasi Goreng Seafood",
        "harga": 15000,
        "cto": "Campur Seafood",
    },
    {
        "kategori": "Makanan",
        "nama": "Nasi Goreng Spesial",
        "harga": 18000,
        "cto": "Ayam + Udang + Telur",
    },
    {
        "kategori": "Makanan",
        "nama": "Nasi Goreng Pedas",
        "harga": 14000,
        "cto": "Level 2 Pedas",
    },
    {
        "kategori": "Makanan",
        "nama": "Nasi Goreng Kambing",
        "harga": 17000,
        "cto": "Bumbu Kambing",
    },
    {
        "kategori": "Makanan",
        "nama": "Nasi Goreng Ikan Asin",
        "harga": 16000,
        "cto": "Dengan Ikan Asin",
    },
    {
        "kategori": "Makanan",
        "nama": "Nasi Goreng Vegetarian",
        "harga": 15000,
        "cto": "Tumis Sayuran",
    },
    {"kategori": "Makanan", "nama": "Nasi Goreng", "harga": 16000, "cto": "Kari Ayam"},
    {
        "kategori": "Makanan",
        "nama": "Nasi Goreng",
        "harga": 13000,
        "cto": "Telur Dadar",
    },
    {
        "kategori": "Makanan",
        "nama": "Nasi Goreng",
        "harga": 17000,
        "cto": "Ayam Bakar + Telur",
    },
    {"kategori": "Makanan", "nama": "Mie Ayam Original", "harga": 10000},
    {
        "kategori": "Makanan",
        "nama": "Mie Ayam Spesial",
        "harga": 12000,
        "cto": "Topping Suwiran Ayam",
    },
    {
        "kategori": "Makanan",
        "nama": "Mie Ayam Bakso",
        "harga": 13000,
        "cto": "Dengan Bakso",
    },
    {
        "kategori": "Makanan",
        "nama": "Mie Ayam Pangsit",
        "harga": 14000,
        "cto": "Tambah Pangsit",
    },
    {
        "kategori": "Makanan",
        "nama": "Mie Ayam Jamur",
        "harga": 15000,
        "cto": "Jamur Crispy",
    },
    {
        "kategori": "Makanan",
        "nama": "Mie Ayam Telur Puyuh",
        "harga": 16000,
        "cto": "Plus Telur Puyuh",
    },
    {
        "kategori": "Makanan",
        "nama": "Mie Ayam Special",
        "harga": 18000,
        "cto": "Ayam + Bakso + Pangsit",
    },
    {
        "kategori": "Makanan",
        "nama": "Mie Ayam Super Pedas",
        "harga": 17000,
        "cto": "Level 3 Pedas",
    },
    {
        "kategori": "Makanan",
        "nama": "Mie Ayam Bakso Seafood",
        "harga": 20000,
        "cto": "Campur Seafood",
    },
    {
        "kategori": "Makanan",
        "nama": "Mie Ayam Cabe Ijo",
        "harga": 15000,
        "cto": "Pedas Cabe Ijo",
    },
]
