menu = [
    {"kategori": "Makanan", "nama": "Mie Ayam", "harga": 10000},
    {
        "kategori": "Makanan",
        "nama": "Mie Ayam",
        "harga": 12000,
        "cto": "Extra Suwiran Ayam",
    },
    {"kategori": "Makanan", "nama": "Bakso", "harga": 10000},
    {"kategori": "Makanan", "nama": "Bakso", "harga": 12000, "cto": "Porsi Jumbo"},
    {"kategori": "Makanan", "nama": "Bakso", "harga": 12000, "cto": "Extra Pentol"},
    {"kategori": "Makanan", "nama": "Ayam Geprek", "harga": 7000},
    {"kategori": "Makanan", "nama": "Ayam", "harga": 6000},
    {"kategori": "Makanan", "nama": "Ayam", "harga": 10000, "cto": "Plus Nasi"},
    {"kategori": "Makanan", "nama": "Ayam Geprek", "harga": 7000, "cto": "Level 1"},
    {"kategori": "Makanan", "nama": "Ayam Geprek", "harga": 7000, "cto": "Level 2"},
    {"kategori": "Makanan", "nama": "Ayam Geprek", "harga": 7000, "cto": "Level 3"},
    {"kategori": "Makanan", "nama": "Ayam Geprek", "harga": 7000, "cto": "Level 4"},
    {
        "kategori": "Makanan",
        "nama": "Ayam Geprek",
        "harga": 12000,
        "cto": "Level 1 + Nasi",
    },
    {
        "kategori": "Makanan",
        "nama": "Ayam Geprek",
        "harga": 12000,
        "cto": "Level 2 + Nasi",
    },
    {
        "kategori": "Makanan",
        "nama": "Ayam Geprek",
        "harga": 12000,
        "cto": "Level 3 + Nasi",
    },
    {
        "kategori": "Makanan",
        "nama": "Ayam Geprek",
        "harga": 12000,
        "cto": "Level 4 + Nasi",
    },
    {
        "kategori": "Makanan",
        "nama": "Ayam Geprek",
        "harga": 10000,
        "cto": "Mozarella",
    },
    {
        "kategori": "Makanan",
        "nama": "Ayam Geprek",
        "harga": 15000,
        "cto": "Mozarella + Nasi",
    },
    {
        "kategori": "Makanan",
        "nama": "Ayam Penyet",
        "harga": 17000,
    },
    {
        "kategori": "Makanan",
        "nama": "Ayam Bakar",
        "harga": 17000,
    },
    {
        "kategori": "Minuman",
        "nama": "Es Teh",
        "harga": 5000,
        "cto": "Tawar",
        "ukuran": "M",
    },
    {
        "kategori": "Minuman",
        "nama": "Es Teh",
        "harga": 7000,
        "cto": "Tawar",
        "ukuran": "L",
    },
    {
        "kategori": "Minuman",
        "nama": "Es Teh",
        "harga": 5000,
        "cto": "Manis",
        "ukuran": "M",
    },
    {
        "kategori": "Minuman",
        "nama": "Es Teh",
        "harga": 7000,
        "cto": "Manis",
        "ukuran": "L",
    },
    {"kategori": "Minuman", "nama": "Jus Jeruk", "harga": 5000, "ukuran": "M"},
    {"kategori": "Minuman", "nama": "Jus Jeruk", "harga": 7000, "ukuran": "L"},
    {"kategori": "Minuman", "nama": "Jus Apel", "harga": 5000, "ukuran": "M"},
    {"kategori": "Minuman", "nama": "Jus Apel", "harga": 7000, "ukuran": "L"},
    {"kategori": "Minuman", "nama": "Kopi Hitam", "harga": 5000, "cto": "Hangat"},
    {"kategori": "Minuman", "nama": "Kopi Hitam", "harga": 5000, "cto": "Dingin"},
    {"kategori": "Minuman", "nama": "Cappuccino", "harga": 5000, "cto": "Hangat"},
    {"kategori": "Minuman", "nama": "Cappuccino", "harga": 5000, "cto": "Dingin"},
    {"kategori": "Minuman", "nama": "Teh Tarik", "harga": 5000, "ukuran": "M"},
    {"kategori": "Minuman", "nama": "Teh Tarik", "harga": 7000, "ukuran": "L"},
    {"kategori": "Minuman", "nama": "Matcha", "harga": 5000, "ukuran": "M"},
    {"kategori": "Minuman", "nama": "Matcha", "harga": 7000, "ukuran": "L"},
]
